### ISSUE TITLE
Incosistent behaviour for teleports between points on the same scene.

### ISSUE THREAD

**Issue by andrewjeffree** [knassher/FVTT-Teleport#1]
If I set up two teleport points on the same scene let's call them A and B, and configure them to teleport to each other. When clicked they change the players perspective but don't seem to move the player token. If I change one of them to teleport to a different scene, use it (it works) and then change it back to the same scene again it starts working. I don't observe any errors in the console when this happening.

**Comment by knassher** [comment]
Could you elaborate a little more, I have tried the scenario that you have described but I have no issues teleporting tokens within a scene.
Thanks

**Comment by andrewjeffree** [comment]
What sort of info do you want? I'm happy to give you access to the world in which I'm testing this if you find me in the Foundry discord (same nickname) I can provide with you access info etc.

**Comment by andrewjeffree** [comment]
Upon retesting again.. it appears to be working now. No idea why, but I'll resolve this for now until I can reproduce it reliably.
