### ISSUE TITLE
Clashing with Better Rolls for 5e?

### ISSUE THREAD

**Issue by HarryJam8** [knassher/FVTT-Teleport#10]
After teleporting one character, whoever performed the teleport can no longer click the image icons from any character to auto-roll. Others who have access to the same character are still able to do so, but as soon as they move the token to a teleportation node and have it teleported, they also cannot click any item image from any character for auto-rolls.
This error code appeared in the console when the item image is clicked.
> Uncaught (in promise) TypeError: Cannot read property 'ctrlKey' of undefined
> at KeyboardManager.isCtrl (foundry.js:2302)
> at CustomItemRoll.checkEvent (custom-roll.js:406)
> at new CustomItemRoll (custom-roll.js:374)
> at Function.newItemRoll (custom-roll.js:340)
> at HTMLDivElement.<anonymous> (betterrolls5e.js:648)
> at HTMLDivElement.dispatch (jquery.min.js:2)
> at HTMLDivElement.v.handle (jquery.min.js:2)

I have disabled Better Rolls and could not replicate the bug. Enabling Minor QoL doesn't seem to create any problem either.
Reload application somehow enabled the auto-rolling again, but as soon as the token gets teleported, the same issue reoccurs.

**Comment by HarryJam8** [comment]
The same error can also be replicated by creating a teleportation node as a GM.
Note: This is 2.1.0.

**Comment by knassher** [comment]
Ok let me check if I could replicate the error. So basically you can't click on anything else after teleporting a token or creating a TP, right?

**Comment by knassher** [comment]
Ok, so when you create a new TP you can select the tokens because you are on the token layer. This is how Foundry works, If you disable Teleport and create a journal entry and then drag that entry over the map you will create a note. If you remain on the note layer you will only interact with note icons. I continue reviewing the error with better rolls

**Comment by knassher** [comment]
Ok, I Have installed better rolls and having better rolls and teleport activated after a few teleportations no errors or not problems click over other tokens or calling the HUD of tokens.
Could you share a step by step of what are you doing to get the error and some screenshots or a video?
Thanks

**Comment by HarryJam8** [comment]
[1. Better Rolls working](https://imgur.com/0Ne0zgQ)
[2. Better Rolls stopped working after creating nodes](https://imgur.com/F54rIGH)
[3. Reloading application working again, can produce better rolls in chat](https://imgur.com/VOF6vMQ)
[4. After teleporting they stopped working again](https://imgur.com/ax5payr)
[5. Only the Roll button works. ](https://imgur.com/UhM6uc5)
[6. Clicking macro hotbar also does not work and shows syntax error](https://imgur.com/4visIpw)
[7. Without Better Rolls, despite the error messages in the console, cards are produces in the chat.](https://imgur.com/xH4F9fd)

**Comment by HarryJam8** [comment]
![1  Better Rolls working](https://user-images.githubusercontent.com/66858784/84579031-a644cc80-ae1e-11ea-9dec-814c2e003d1e.PNG)
![2  Better Rolls stopped working after creating nodes](https://user-images.githubusercontent.com/66858784/84579038-b0ff6180-ae1e-11ea-9606-61e43b00dfbf.PNG)
![3  Reloading application working again, can produce better rolls in chat](https://user-images.githubusercontent.com/66858784/84579047-c1afd780-ae1e-11ea-9083-598a1056148f.PNG)
![4  After teleporting they stopped working again](https://user-images.githubusercontent.com/66858784/84579051-c7a5b880-ae1e-11ea-9eb1-10e7919f669e.PNG)
![5  Only the Roll button works](https://user-images.githubusercontent.com/66858784/84579052-cd9b9980-ae1e-11ea-9c5e-74bb310a12d1.PNG)
![6  Without Better Rolls, despite the error messages in the console, cards are produces in the chat](https://user-images.githubusercontent.com/66858784/84579057-d7bd9800-ae1e-11ea-8d82-d1494bb21814.PNG)

**Comment by HarryJam8** [comment]
I also screencaptured it as a video but the webm is over 20mb and the gif is over 60mb big, sorry :S

**Comment by knassher** [comment]
Ok, thanks for the info! First, how do I enable the buttons that are on top
on the screen, sorry to ask you this but I have never used better rolls so
I don't know how to use it.

I think where on my code is causing the issue, could you try using this
version and let me know if the issue persists?

Remove or comment this line this.generateCanvasHoverInEvent(); on the
teleportpoint.js

thanks

**Comment by HarryJam8** [comment]
Oops! Sorry I should have mention this earlier. The buttons that are on top are from another mod known as ["Token Bar" by kekilla](https://github.com/Kekilla0/TokenBar). It is like a hotbar that outputs the same chat message when clicking the item image. Better Rolls doesn't do that, it changed the output/item card in chat. The two are compatible so clicking the buttons on top does the same thing as clicking item image.
I commented this.generateCanvasHoverInEvent(); on the teleportpoint.js, and the item images are now functional before AND after teleporting the token. It worked! Cheers!
They are still unresponsive after I created teleport nodes, but that is much more manageable in comparison. I simply have to reload application after making all the nodes I want during my preparation, then I do not have to worry about it in the actual session. That is amazing :D

**Comment by knassher** [comment]
Glad to hear that! Either way I will work on that I think I have an idea of
how to fix it. Once I have a new version, I'll contact you so you can test
it and see if the fix works.

Thanks

**Comment by knassher** [comment]
Hey man, I think I got it, I have run some tests using the add-ons you have
mentioned and removing the line of code I pointed out and everything worked
perfectly. No errors from better rolls and tokens and token bar worked
without freezing.

Please update the module and let me know if you have found any problems.

Thank

**Comment by HarryJam8** [comment]
I didn't find any problem after the 2.1.1 update, whether it's creating the nodes or teleporting the tokens. Cheers Knassher! This module is amazing.
