### ISSUE TITLE
Support mouse movement

### ISSUE THREAD

**Issue by MSAbaddon** [knassher/FVTT-Teleport#11]
Currently the teleport points only activate if a token is placed above them using the cursor buttons. It'd be nice if movement using the mouse would also trigger teleports.

**Comment by knassher** [comment]
Hi MSAbaddon,

Actually there are 3 ways to trigger a teleport point:
1.- Using arrow keys
2.- Selecting a token then double left click on a teleport point
3.- Draggin a token using the middle button of the mouse and drop it over a
teleport point.

Please let me know if any of the 3 options is the one you are looking for.

Thanks

**Comment by MSAbaddon** [comment]
Hi,
thanks for the reply. Overlooked the middle mouse button option, that's exactly what I was looking for :-)
Do you have any plans of adding an option to switch this functionality to the left mouse button?

**Comment by knassher** [comment]
Yes, but I will have to recode some functionality!

Let you know if I figure it out.

Thanks

**Comment by MSAbaddon** [comment]
Thats's great news, thanks for the reply and the great module you created :-)
