### ISSUE TITLE
Pan sometimes bugs.

### ISSUE THREAD

**Issue by rinnocenti** [knassher/FVTT-Teleport#15]
When you have 3 teleports (each leads to the other)
if you are from A-> B-> C and then C-> B-> A the teleport works well, however, if you are in B and try to return to the point you came from (eg C-> B-> C), the token is teleported but the Pan is on the teleport you left.
the teleports are working together with the Pan if it always follows for a new teleport, however if I return, the Pan sometimes updates in the same place, sometimes not.
to reproduce, just leave the teleports nearby so that you can travel quickly.

**Comment by knassher** [comment]
Thanks for the report, I have notice this issue too but just when you move a token with the arrows keys, if you do teleport a token with double left click over a tp this behavior doesn't occur.
I'm reviewing the code to determine why this is happening, but I think I have a clue on where the issue might be.

**Comment by knassher** [comment]
version 2.1.3 fixes the problem.
