### ISSUE TITLE
When 2 teleport icons are next to eachother the module doesnt function after the first teleport

### ISSUE THREAD

**Issue by Alsci** [knassher/FVTT-Teleport#17]
I want to use the module to create functioning stairs. It works okay when I set it up to go in one direction and I can repeatedly move the token to the square causing it to teleport. Although when I set it up so theres a downwards direction too (off set by a single tile). After the first teleport the module doesnt seem to work.

![image](https://user-images.githubusercontent.com/67440473/85952878-2feab300-b964-11ea-9056-bdea0942d036.png)

**Comment by knassher** [comment]
Hey, can you give me more details of the issue? How are you triggering TPs?
arrows keys, double left click or drag & drop?

I have setted a very similar scenery like the one you are describing and
it's working properly.

A little bit of info would be nice!

Thanks
