### ISSUE TITLE
Teleport not working for my players just the server version.

### ISSUE THREAD

**Issue by DandDPM** [knassher/FVTT-Teleport#18]
The teleport module is not working for players on their web browser.  It works on my DM server version and teleports to the correct spots for stairs etc.  I have already tried disabling all other modules to see if there was interference and it still happens.  I am running core 0.6.4 and Teleport 2.1.3.  It does not indicate a compatibility risk.  Do I as the DM have to move the token onto the teleport journal entry or should the player be able to do it?
My players get a notification when they log in that the teleport locations are loading, which makes me think it should work for them.
Edit:  I was just told on discord that my players need to click the icon, but it is not present on google chrome.  See images below.
![image](https://user-images.githubusercontent.com/65044691/85954294-60baf000-b944-11ea-9fcd-358e4d5b8647.png)

**Comment by knassher** [comment]
Hey, have you granted access to the journal entry tied to the teleport
point to your PCs?

Thanks

**Comment by DandDPM** [comment]
I did not.  I didn't see it in the instructions.  I have now given them owner permissions and clicked to show markup for them and it works.  Thank you.
