### ISSUE TITLE
Teleport Scene change affecting entire party

### ISSUE THREAD

**Issue by tcflanag** [knassher/FVTT-Teleport#19]
I'm trying to implement stairs in a building, however as soon as one person moves onto the trigger, the entire party is pushed to the new scene (though the GM stays put).  Is it possible to only move the one person, so the party can split?

**Comment by knassher** [comment]
Hey, could you give me more details so that way I can recreate the issue?
1.- who is triggering the TP? GM or PC?
2.- when the TP is triggered all the party is controlled by the user who
triggered the PC?
3.- how the TP is triggered? Arrows key, drag and drop or double left click?

Thanks

**Comment by knassher** [comment]
V 2.1.5 fixes the issue.
Enjoy

**Comment by tcflanag** [comment]
Nice!  I was just reproducing on a clean setup to write you a proper bug
report when I saw your fix come in.  I've updated and it appears to be
working like I would expect now.

Thanks for the quick update!
