### ISSUE TITLE
FVTT-Teleport conflicts with Pings module

### ISSUE THREAD

**Issue by Azzurite** [knassher/FVTT-Teleport#2]
When https://gitlab.com/foundry-azzurite/pings is enabled together with this module, Pings [breaks](https://gitlab.com/foundry-azzurite/pings/-/issues/6).

To fix it, could you please remove this line:

https://github.com/knassher/FVTT-Teleport/blob/af255031a477bda631ebdf7a07d639487fa1e382/scripts/teleportpoint.js#L233

I also have a `mouseUp` handler registered, which needs to run. If you stop propagation, my handler doesn't run so my module breaks.

Generally, you only want to use `stopPropagation` on events that *you triggered yourself*. If a user triggered a normal browser event, you normally never want to stop propagation.

(I'm the dev of Pings, btw :) )

**Comment by knassher** [comment]
Hey man,

Sorry to hear that, I just made an update to my module removing the line
you mentioned. Hope this helps you.

Thanks

Renzo

**Comment by knassher** [comment]
Changes were made. Closing ticket
