### ISSUE TITLE
Modules "TELEPORT" & "NO TOKEN ANIMATIONS" conflict

### ISSUE THREAD

**Issue by ColombianJulio** [knassher/FVTT-Teleport#20]
hello! love your module for foundry. I realized though that when activated, it overwrites the functionality of another module that removes token animation when you drag and drop tokens. would really like to see this fixed.
![11](https://user-images.githubusercontent.com/67991100/86872188-bfe9d480-c0a9-11ea-81fa-19bf06ced112.gif)
![22](https://user-images.githubusercontent.com/67991100/86872192-c1b39800-c0a9-11ea-94db-504fe8d465fd.gif)

**Comment by knassher** [comment]
V 2.1.6 fixes the issue.
