### ISSUE TITLE
PLEASE FIX! your module permantely deletes journal entries!

### ISSUE THREAD

**Issue by ColombianJulio** [knassher/FVTT-Teleport#21]
whether I hit the delta button to remove a journal from the scene or use the tool to clear objects from the scene, it also delete the journal entries themselves!
![Screen-Recording-2020-07-08-at-2 17 55-PM](https://user-images.githubusercontent.com/67991100/86958176-c3bd3b80-c129-11ea-8971-2321c05825b7.gif)

**Comment by knassher** [comment]
V 2.1.6 fixes the issue.
