### ISSUE TITLE
DM can always teleport token , but PC can do it one time only

### ISSUE THREAD

**Issue by Hantar0** [knassher/FVTT-Teleport#22]
Hello, I create 4 token. 
Enter_in
Enter_out
Exit_in
Exit_out

When the PC walk on Enter_in, he is tp to Enter_out. And when he enter on Exit_in, he is tp on Exit_out.

Using Foundry app as gamemaster make it work nice, I can use both TP all the time. 
But, using it with a browser, as PC, allow me to do it once each. Then it won't tp me anymore. 
(I still can tp with gamesmaster account)
The only way to reset, it's to change the permission to something else (owner, observer or limited)

But I really wanted my player, to go in or go out all the time...

Good luck with the issue.

**Comment by Friboren** [comment]
I have the same exact issue.

**Comment by knassher** [comment]
It this issue occurs when you set your TPs on a same scene o with different scenes? Have you granted access to all your TPs to your players?

**Comment by Hantar0** [comment]
Hello.

I made some tests.

Both tp on same scene or one scene to an other have the issue.

I create a tone of TP (prepare many map before finding the issue). I gave my player "Observer" on all, but it won't work.
I verify that all the TP are listed in player articles. But they can't TP by themself.
If change the right to "Limited", or "Owner", it work again, but for one time. :/

Sorry, I can't help you more. If they're some logs that I can give you, juste ask for it. :)

PS : Is there a way, that player don't see the tp in the articles ? Them seeing : tp _to_secret_camp, is kinda akward information.

**Comment by Hantar0** [comment]
For more testing, I create a new word, 1 scene, 1 player, 2 tp. Still the issue.

Trying with : "Observer" for all player on both, "Owner" for all player on both, "Observer" for only player1 and "Owner" only for player1.

Don't know how to test more.

(Try both on Firefox and Chrome)

**Comment by knassher** [comment]
I'll give it a look.

**Comment by knassher** [comment]
So, I have created a similar scenario, two TPs on same scene and one token with access as observer for both TPs.

![image](https://user-images.githubusercontent.com/60122278/87233981-4b0ce800-c392-11ea-8ca1-c432197d7135.png)

Config for A:
![image](https://user-images.githubusercontent.com/60122278/87234005-7abbf000-c392-11ea-81cd-b29e39cffd08.png)

Config for B:
![image](https://user-images.githubusercontent.com/60122278/87234023-ab038e80-c392-11ea-9a4b-8299299e37d2.png)

Then I access as PC with player role and I can tp from point A to B and vice versa without issues.
![image](https://user-images.githubusercontent.com/60122278/87234069-05045400-c393-11ea-843f-35048d81b058.png)

![image](https://user-images.githubusercontent.com/60122278/87234081-14839d00-c393-11ea-8215-7502093bf753.png)

The module doesn't verify permissions, this is part of the core, and doesn't limit how many times you can move between TPs. Perhaps there is a wrong set up of the TPs, are you receiving any errors? Perhaps a conflict with another module?

If you could send me the config of each TP and a video of the PC that would help.

Thanks

**Comment by Hantar0** [comment]
Hello, 

My mistake was on this :

"To see note on a scene you need:

    Have access to the journal entries associeted with the notes you want your PCs to see.
    Toogle the "Notes Display" button on the Journal control bar.
"
I'm really sorry, I didn't understand this point at first because it was partly working. -_-

Moreover, I didn't need to "GM needs to grant "Observer" permission to the PC", only if the GM want the player to see the token. So it's kinda cool if they don't see it, so no note showing in articles. ;)

Thanks for the goodwork !
I love your job !

**Comment by knassher** [comment]
Great to hear!
