### ISSUE TITLE
Combat tracker not functioning with module enabled

### ISSUE THREAD

**Issue by Phonochirp** [knassher/FVTT-Teleport#23]
On foundry version 0.6.5, dnd 5e 0.93, when module is enabled the combat tracker tab is replaced 
with a plain grey block. ![image of bug](https://user-images.githubusercontent.com/68512117/87880824-773fee80-c9ba-11ea-8129-440ab5cbcbaf.png). Only module installed is teleport, disabling the module fixes issue. 

Started a completely fresh world, and was able to duplicate the issue.

**Comment by Freelancerjw** [comment]
I too am experiencing this issue. Foundry 0.6.5, sfrpg 0.3.5.

**Comment by knassher** [comment]
Are you using Teleport with other modules?

**Comment by Phonochirp** [comment]
No, teleport is the only module installed

**Comment by knassher** [comment]
@Phonochirp can you send me the error shown on the console log?

**Comment by Freelancerjw** [comment]
I was, I haven't tested it by itself personally. I can upload a log later.

**Comment by Phonochirp** [comment]
![image](https://user-images.githubusercontent.com/68512117/89212266-ca07d180-d588-11ea-908d-14c24ce7ede1.png)

I believe this is the error?

**Comment by knassher** [comment]
Yes, I think I have found where the issues is. So I'll release a new version soon. Let you know when is done so you can validate if that fixes the problem. Thanks

**Comment by knassher** [comment]
@Phonochirp, please try version 2.1.7, this should be fixing the combat tracker issue.

**Comment by Freelancerjw** [comment]
Fixed on my end, thanks!

**Comment by Phonochirp** [comment]
Yup, did the trick, thanks!
