### ISSUE TITLE
Unable to use Teleport mod

### ISSUE THREAD

**Issue by Darkvulpine** [knassher/FVTT-Teleport#24]
I installed the mod, tried to follow the instructions.  However, I only see the Journal Entry and Folder for teleport Points.
Adding a new one only just makes a basic journal page.

**Comment by knassher** [comment]
What version are you using of the module and foundry? Do you see any errors
on the chrome console?
Also are you enabling the "Add TP" buttons?
[image: add_tp.PNG]
It's a toggleable button, so you have to toggle it first in orden to add TP
(turns purple when is toggled), if you don't do that you will be adding
single notes to the scene.

**Comment by Darkvulpine** [comment]
Foundry 0.6.5
Teleport 2.1.7
I don't see an "add TP" button.
It just looks like a normal journal entry.   I have the module enabled, I can configure settings: "Hide Departing Tokens" "Activate Scene"
The journal tab just has a folder: "Teleport points" with a page "Teleportation" I can add new pages, but I do not see "add TP"
![Capture](https://user-images.githubusercontent.com/69316348/89571512-cd53c500-d7f5-11ea-9778-2bbebe4b745f.PNG)

**Comment by baberg** [comment]
I am having the same issue.  

Foundry 0.6.5
Teleport 2.1.7
PF2E game system 1.9.5.1620 

Same symptoms.  There is no "Add TP" button that I can see on the Journal page.  This is the first time I've tried loading it up.  No console errors I can see.

**Comment by knassher** [comment]
The button is located on the control bar (left bar).

[image: left_bar.PNG]

**Comment by knassher** [comment]
@baberg & @Darkvulpine, are you still having issues with the module?

**Comment by baberg** [comment]
Sorry, I just started using a different module to handle the teleportation effects.  Hopefully it was just our user error that caused our issues.

Have a good one.

**Comment by Darkvulpine** [comment]
I honestly gave up.
I still need a HERO System plugin for what I want to do.

**Comment by Darkvulpine** [comment]
but I was able to at least add a point, but had issues configuring it to other points.
