### ISSUE TITLE
Teleport module breaks token vision in 0.7.1

### ISSUE THREAD

**Issue by LeRatierBretonnien** [knassher/FVTT-Teleport#25]
To reproduce : 
 - Enable Teleport with a teleport node
 - Set a player token somewhere in the scene
 - Set its vision radius
 - Enable the Fog of War on the scene
 - Move the token on the scene 
-> the token vision is not moving, it remains a the same place (ie not following the token).

When deactivating 'Teleport', the behavioris OK.

**Comment by knassher** [comment]
I didn't update the module to 0.7.1 yet and I'm not going to do it until
foundry reaches beta.

So version 0.7.0 and 0.7.1 are not supported yet.

**Comment by LeRatierBretonnien** [comment]
Yes, understood, but i am 100% sure that this issue will still be in the beta 0.7.X, as it seems related to the big changes that occured in the API.

**Comment by InflamedSebi** [comment]
7.3 just reached beta and this issue still persists.
- Tokens that emit light, will not move their light source with them until you switch to the lighting layer, which will trigger a single update every time you do so.
- Token vision suffers from the exact same issue.
- Enabling the 'Token Drag Vision' option, forces updates on token vision as a workaround. Solely updates the vision, not the emitted light.
