### ISSUE TITLE
Players can see more stuff than I would like them to

### ISSUE THREAD

**Issue by Alexis-Grimm** [knassher/FVTT-Teleport#26]
If I need to give players permission for the journal note (Observer) for the teleport spot, and these teleport spots are in folders named after the scene they are in. This kinda tells my players a lot about aspects of the scene, like how what kind of exits they are, how many they are, and what the scenes are named, even when I have given my scenes different appearances in the navigation bar specifically to avoid this. Any solution to this?

**Comment by knassher** [comment]
Folders are created using the Navegation name of the scene, in case of this field is empty then the scene name is used.

Unfortunately foundry doesn't offer a way to hide folders or journals to players once they have access to it. A work around would be renaming the folders and entries, or give them the access at specific moments.

I'll check if is I there is a way to not render the folders and their content but it will take time.
