### ISSUE TITLE
Teleportation Only Works Once

### ISSUE THREAD

**Issue by illcom94** [knassher/FVTT-Teleport#27]
Running Foundry VTT 0.6.5.
Place a teleport from one map to another.
Once a player uses the keyboard to move into the teleport they move to the other map. They try and move back using the reverse of the teleport and nothing happens. Other player tokens can't use the teleport afterwards. I either need to update the teleport entry which sometimes works, or delete them and create new ones.

**Comment by knassher** [comment]
Can you share some screenshots or a video of the problem, I can't replicate what you are describing. Don't have that issue.
So keep in mind the following:
- If you want to go back and forward with two TPs, TP1 needs to reference TP2 and TP2 needs to reference TP1. To do that on TP1  the field  "To Scene" has to be populated with name of the map where TP2 is located and the field "To Note" populated with the name of TP2. On TP2 you have to do the opposite,  "To Scene" name of the map of TP1 and "To Note" name of the TP1.
- Make sure that your PC has "Observer" permission to both TPs.
- Make sure that the Player Role has permission to create tokens.
- Make sure that your PC has the "Toggle Display Notes" button on.

**Comment by illcom94** [comment]
Hey, looks like all of those things fixed my issues for the multi-map scenario. Thanks! Some of these settings were difficult for me to find. Thanks for your help!

**Comment by illcom94** [comment]
All works as expected after I applied all of knassher's suggestions.
