### ISSUE TITLE
Feature Request: Activation Options

### ISSUE THREAD

**Issue by illcom94** [knassher/FVTT-Teleport#28]
I would love the ability to set the activation of a teleport to be only activated when someone double clicks on it. That way when I put stairs down on a map, players can still put their token there without activating it unless they want to.

**Comment by knassher** [comment]
Actually the module already support that, there are 3 ways to trigger a tp,
by double clicking it with the left button, moving a token with the
keyboard and moving a token using drag and drop with the middle button.

**Comment by illcom94** [comment]
Hi! Thanks for replying. Yes, it does. However I would like to option to disable the trigger when a token moves on top with the arrows. Or maybe the ability for it to ask them if they want to continue or something like that.

**Comment by knassher** [comment]
Thanks for the clarification.
