### ISSUE TITLE
Do not activate scene every time a character takes a teleport

### ISSUE THREAD

**Issue by jflevesque** [knassher/FVTT-Teleport#29]
Would it be possible to pull a player to a scene instead of activating the scene for everyone? It is very annoying when a character takes a teleport between scenes during combat, because everyone gets moved to a different scene.

**Comment by knassher** [comment]
There is a setting that allows you to not activate the scene. By default
activates the scene if the GM uses a TP, if you disable this settings then
no activation will be performed.

**Comment by jflevesque** [comment]
Ah, you are right, just saw that in the module settings. I should have checked before opening the issue. Thank you for your quick response!
