### ISSUE TITLE
one particular box, not in the middle of 4 boxes

### ISSUE THREAD

**Issue by altair984** [knassher/FVTT-Teleport#30]
hello i would like to know if there is any way to make the token when teleporting can do it in a certain box.

whenever the new icons appear they do so at the central point of 4 boxes

https://i.imgur.com/mCdI3Xw.png

I would like that when the character teleports, he does it in the center of a single box. is it possible?

https://i.imgur.com/HyVuiO6.png

Thanks for all ^^

**Comment by knassher** [comment]
You can set the offset for tokens arrivals, bu that would apply to all
tokens who use that particular TP.

You will find the offsets on the config TP form, in there, just click the
offset tap.

Thanks
