### ISSUE TITLE
The module breaks token vision updating from the DM perspective. (v0.7.3)

### ISSUE THREAD

**Issue by Drills** [knassher/FVTT-Teleport#35]
The module breaks token vision updating from the DM perspective.  
When I enable the module with the latest beta version, I noticed that the if I move a token as the DM the vision is not updated unless I unselect the token and then re-select it.

This makes it hard to move tokens when using LOS.

**Comment by jcolemanquotient** [comment]
It also appears to break vision from the player's perspective, from my experiences today on the Beta Release version 7.3.

**Comment by knassher** [comment]
Hi, thank you for using the module, but unfortunately, I don't have time to maintain the modelue anymore so I've decided to archive the project.

Sorry for any inconvenience.
