### ISSUE TITLE
Logout Resetting

### ISSUE THREAD

**Issue by Perlsowisdom** [knassher/FVTT-Teleport#4]
Every time I log out of my game then log back in, none of my teleport points work. The data still shows it's there, they just don't do anything when I click on them.

**Comment by knassher** [comment]
Can you provide more details on your issue please, like screenshots or any
errors on the console.

Thanks

**Comment by Perlsowisdom** [comment]
I figured it out. I didn't realize that an actual note was being created, or where it was being stored. When I imported new scenes from the DDB connector, the folder it was being saved in kept overwriting my teleport journal. Not an app problem, or even a compatibility problem. I just need to reconfigure where I'm saving things and my naming scheme.

**Comment by knassher** [comment]
Glad to hear that. If you find any issues, please let me know.

Thanks
