### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Princess-Cheeseballs** [knassher/FVTT-Teleport#5]
Not a bug report, but I would like to in the future be able to make teleport points that can be seen globally by all players similar to how you can make Map Notes viewable by all players. 

The module is great by the way, so far in my testing I've had no issues and it's been exactly what I've needed for my map creation.

**Comment by knassher** [comment]
Actually TPs are based on map notes so you can make it available to
everyone.

To do that you just need to give observer rights to the Teleportation
journal.

Thanks

**Comment by Princess-Cheeseballs** [comment]
Ah, I see it now. Is there any way to change the visibility of specific teleports or is it only global?

**Comment by ghero101** [comment]
One Comment on this, would be you have to allow all the TPs to visible or none of them. I personally would like to have greater control over what TPs players can see. Some for example may be hidden room, vs just the staircase between levels of a dungeon. Unless I am missing something with the way permissions work.

**Comment by knassher** [comment]
At the moment its only global.

**Comment by knassher** [comment]
> One Comment on this, would be you have to allow all the TPs to visible or none of them. I personally would like to have greater control over what TPs players can see. Some for example may be hidden room, vs just the staircase between levels of a dungeon. Unless I am missing something with the way permissions work.

At the moment all TPs are tied to 1 journal entry, enable access to this entry makes it possible for PCs to see the TPs on all maps, I would have to investigate if I can hide notes similar to what we have right now with tokens, or perhaps create a journal entry for each TP.

I will have to think more about it.

**Comment by knassher** [comment]
Version 2.1.0 will create a Journal entry per TP, that will give you control on what TP you show to your PCs.
