### ISSUE TITLE
Auto Activation Feature Request

### ISSUE THREAD

**Issue by ghero101** [knassher/FVTT-Teleport#6]
I would like to see a collision detector between the TP object and any/all actor tokens. This way as a player or npc moves through a map running over what would appear as just a staircase would automatically transport them to the new destination without having to select and drop. This would provide for a much more fluid experience without having to mess around with another mod like TriggerHappy, which I can see as very cumbersome for most users.

**Comment by knassher** [comment]
Hey man, thanks for your suggestion, I think is doable, just need to figure
it out how Foundry is handling keystroke.

Thanks again

**Comment by knassher** [comment]
I just released version 2.0.8, in this version when you move a token with the keyboard and hit a TP the teleportation is triggered.
