### ISSUE TITLE
Disable Animation for Teleport

### ISSUE THREAD

**Issue by Nordiii** [knassher/FVTT-Teleport#7]
I would love the option to disable the Animation when you teleport on the same scene!

Probably do able with this:
https://foundryvtt.com/api/Token.html#_noAnimate

**Comment by knassher** [comment]
The module actually has some lines that use the _noAnimate to stop the animation when the token is teleported on the same scene but it seems that this property is not working.

In you set it manually on the console the animations are still executed so there must be a bug in the core.

**Comment by knassher** [comment]
There is a new feature that disables the animation.
