### ISSUE TITLE
Token is not selected after teleport

### ISSUE THREAD

**Issue by Nordiii** [knassher/FVTT-Teleport#8]
The player looses the focus on the token when teleporting (at least on the same scene).
Would be awesome if you could move it again with the arrow keys without reselecting the token!

**Comment by ExileofBrokenSky** [comment]
This suggestion would make it perfect.

**Comment by knassher** [comment]
Lost of focus was on purpose due to some issues on version 1.00; I guess I could give a look again and see if I can do it with breaking anything.
Thanks

**Comment by ghero101** [comment]
If you are able to do this it would go a long way with your update from 2.0.8 since a players can now interact with a token and be teleported automatically using the directional keys keeping focus would help with consistency..

**Comment by knassher** [comment]
v 2.0.9 has been released, in this version tokens remain controlled after a teleportation.
